
spring:
  application:
    name: Demo1

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        generate_statistics: true
        event:
          merge:
            entity_copy_observer: allow
        show_sql: false
        use_sql_comments: false
        format_sql: false
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        # MS SQL SERVER
        #dialect: org.hibernate.dialect.SQLServer2008Dialect
        jdbc:
          time_zone: UTC
          batch_size: 50
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?verifyServerCertificate=false&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver


logging:
  config: src/main/resources/log4j2.yaml

debug: false